In [1]:
import numpy as np
import biobox as bb

In [7]:
m = bb.Molecule('/Users/josh/Downloads/SASDVT5_fit2_model1.pdb')
df = m.data

In [8]:
df[ df['name'] == 'CA' ]

,atom,index,name,resname,chain,resid,occupancy,beta,atomtype,radius,charge
1,ATOM,1,CA,THR,A,52,1.0,0.34,C,1.7,0.0
8,ATOM,8,CA,GLY,A,53,1.0,0.46,C,1.7,0.0
12,ATOM,12,CA,LEU,A,54,1.0,0.58,C,1.7,0.0
20,ATOM,20,CA,ASP,A,55,1.0,0.64,C,1.7,0.0
28,ATOM,28,CA,PRO,A,56,1.0,0.68,C,1.7,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3096,ATOM,3096,CA,GLU,A,464,1.0,0.68,C,1.7,0.0
3105,ATOM,3105,CA,LEU,A,465,1.0,0.63,C,1.7,0.0
3113,ATOM,3113,CA,VAL,A,466,1.0,0.56,C,1.7,0.0
3120,ATOM,3120,CA,SER,A,467,1.0,0.53,C,1.7,0.0
3126,ATOM,3126,CA,THR,A,468,1.0,0.39,C,1.7,0.0

In [9]:
seq = 'TGLDPQLWHACAGGMVQLPPVGAKVIYFPQGHGEQAATPPEFPRMMGPQGTIGCRVVSVSFLADTETDEVYARIRLQPLEREAAMSIADSTLDADGGPSSPPPEKPASFAKTLTQSDANNGGGFSVPRYCAETIFPPLDYSIDPPVQTVLAKDVHGERWKFRHIYRGTPRRHLLTTGWSTFVNQKKLVAGDAIVFLRTASGELCVGVRRSMRGTGGADSSTWSGGSSTSHHRPNRWEVKGTESFSDFLGNDSAAGGGSVSSAGSAAGPGGPRAGPGGSNSGPGIGIPGPSTTSSFARNRARVTAQSVLEAASLAVQGQPFEVVYYPRASTAEFCVKAQAVKAALDHTWFPGMRFKMAFETEDSSRISWFMGTISAVQPADSLWPKSPWRVLQVTWDEPDLLQGVSRVSPWQVELVSTLPGNSYSQSM'

In [10]:
len( seq )

427